job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include(('portal_user_app.urls', 'portal_user_app'))),
    path('admin/', include(('portal_admin_app.urls', 'portal_admin_app'))),
    path('resume/', include(('portal_resume_app.urls', 'portal_resume_app'))),
    path('converter/', include(('portal_converter_app.urls', 'portal_converter_app'))),
    path('tracking/', include(('portal_ats_app.urls', 'portal_ats_app'))),
    
    path('', include('django_prometheus.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal_resume_app/urls.py
from django.urls import path
from . import views

app_name = 'portal_resume_app'

urlpatterns = [ 
    # ================================
    #        Index Page and Form Submissions
    # ================================
    path('index/', views.resume_index_view, name='resume_index'),

    # ================================
    #        Save Resume
    # ================================
    path('save/', views.resume_save_view, name='resume_save'),

    # ================================
    #        List All Resumes
    # ================================
    path('list/', views.resume_list_view, name='resume_list'),

    # ================================
    #        View Specific Resume
    # ================================
    path('view/<int:resume_id>/', views.resume_display_view, name='resume_display'),

    # ================================
    #        Download Resume as PDF
    # ================================
    path('download/<int:resume_id>/', views.resume_download_view, name='resume_download'),

    # ================================
    #        Delete Resume Fields
    # ================================
    path('delete/hobbie/', views.delete_hobbie_view, name='resume_del_hob'),
    path('delete/skill/', views.delete_skill_view, name='resume_del_skill'),
    path('delete/certificate/', views.delete_certi_view, name='resume_del_certi'),
    path('delete/project/', views.delete_pro_view, name='resume_del_pro'),
    path('delete/language/', views.delete_lang_view, name='resume_del_lang'),
    path('delete/experience/', views.delete_exp_view, name='resume_del_exp'),
    path('delete/education/', views.delete_edu_view, name='resume_del_edu'),

    # ================================
    #        Test Resume Template
    # ================================
    path('test/', views.resume_test_view, name='test')
]

portal_resume_app/views.py
# ================================
#        Django Imports
# ================================
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from io import BytesIO
from django.core.files.base import ContentFile
from .models import *
from .utils import get_user_data
import imgkit
import pdfkit
import json

# ================================
# View to Handle Resume Index Page and Form Submissions
# ================================
@login_required(login_url='portal_user_app:user_login')
def resume_index_view(request):
    """
    Handle requests to the resume index page. This view processes form submissions
    to update personal information, education, experience, languages, projects, 
    certificates, skills, hobbies, and summaries. It also renders the resume 
    index page with the user's data.
    """
    if request.method == 'POST':
        response_data = {}
        try:
            # Personal Information Update
            if 'name' in request.POST:
                name = request.POST.get('name')
                email = request.POST.get('email')
                phone = request.POST.get('phone')
                address = request.POST.get('address')
                user = get_object_or_404(User, id=request.user.id)
                PersonalInfo.objects.update_or_create(user=user, defaults={
                    'name': name, 'email': email, 'phone': phone, 'address': address
                })
                response_data['message'] = 'Personal Information updated successfully!'
            
            # Education Information Update
            elif 'degree1' in request.POST:
                degree = request.POST.get('degree1')
                college = request.POST.get('college1')
                year = request.POST.get('year1')
                cgpa = request.POST.get('cgpa1')
                user = get_object_or_404(User, id=request.user.id)
                Education.objects.create(user=user, degree=degree, college=college, year=year, cgpa=cgpa)
                response_data['message'] = 'Education Information updated successfully!'

            # Experience Information Update
            elif 'role1' in request.POST:
                role = request.POST.get('role1')
                company = request.POST.get('company1')
                year = request.POST.get('year1')
                location = request.POST.get('location1')
                description = request.POST.get('description1')
                user = get_object_or_404(User, id=request.user.id)
                Experience.objects.create(user=user, role=role, company=company, year=year)
                response_data['message'] = 'Experience Information updated successfully!'
            
            # Language Information Update
            elif 'language1' in request.POST:
                language = request.POST.get('language1')
                user = get_object_or_404(User, id=request.user.id)
                Language.objects.create(user=user, language=language)
                response_data['message'] = 'Language Information updated successfully!'
            
            # Project Information Update
            elif 'project1' in request.POST:
                project_title = request.POST.get('project1')
                description = request.POST.get('project_description1')
                user = get_object_or_404(User, id=request.user.id)
                Project.objects.create(user=user, title=project_title, description=description)
                response_data['message'] = 'Project Information updated successfully!'
            
            # Certificate Information Update
            elif 'certificate1' in request.POST:
                certificate = request.POST.get('certificate1')
                year = request.POST.get('certificateyear1')
                user = get_object_or_404(User, id=request.user.id)
                Certificate.objects.create(user=user, certificate=certificate, year=year)
                response_data['message'] = 'Certificate Information updated successfully!'
            
            # Skill Information Update
            elif 'skill1' in request.POST:
                skill = request.POST.get('skill1')
                user = get_object_or_404(User, id=request.user.id)
                Skill.objects.create(user=user, skill=skill)
                response_data['message'] = 'Skill Information updated successfully!'

            # Hobbie Information Update
            elif 'hobbies1' in request.POST:
                hobbie = request.POST.get('hobbies1')
                user = get_object_or_404(User, id=request.user.id)
                Hobbie.objects.create(user=user, hobbie=hobbie)
                response_data['message'] = 'Hobbie Information updated successfully!'
            
            # Summary Information Update
            elif 'description2' in request.POST:
                description2 = request.POST.get('description2')
                user = get_object_or_404(User, id=request.user.id)
                Summary.objects.update_or_create(user=user, defaults={
                    'description': description2,
                })
                response_data['message'] = 'Summary Information updated successfully!'

            return JsonResponse({'success': True, 'message': response_data.get('message', 'Data saved successfully!')})

        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)})

    # Fetch all the data to render the template
    personal_data, education_data, experience_data, language_data, project_data, certificate_data, hobbie_data, skill_data, summary_data = get_user_data(request.user)
    
    return render(request, "portal_resume_app/resume_index.html", {
         'personal_data': personal_data,
         'education_data': education_data,
         'experience_data': experience_data,
         'language_data': language_data,
         'project_data': project_data,
         'certificate_data': certificate_data,
         'hobbie_data': hobbie_data,
         'skill_data': skill_data,
         'summary_data': summary_data
    })

# ================================
# View to List All Resumes
# ================================
def resume_list_view(request):
    """
    Render a page listing all resumes for the logged-in user.
    """
    resumes = Resume.objects.filter(user=request.user)
    return render(request, "portal_resume_app/resume_list.html", {'resumes': resumes})

# ================================
# View to Download Resume as PDF
# ================================
def resume_download_view(request, resume_id):
    """
    Handle the request to download a specific resume as a PDF file.
    """
    try:
        # Retrieve the resume object
        resume_download = Resume.objects.get(id=resume_id)

        # Configure pdfkit with path to wkhtmltopdf executable
        pdfkit_config = pdfkit.configuration(wkhtmltopdf=settings.PDFKIT_CONFIG['wkhtmltopdf'])

        # Options to set paper size and other settings
        options = {
            'page-width': '2480px',  # Width in pixels (matching A4 size at 300 DPI)
            'page-height': '3508px',  # Height in pixels (matching A4 size at 300 DPI)
            'margin-top': '0mm',
            'margin-right': '0mm',
            'margin-bottom': '0mm',
            'margin-left': '0mm',
            'zoom': '1.50',  # Matching zoom level with image options
            'print-media-type': '',
            'orientation': 'Portrait',
            'enable-local-file-access': '',
            'dpi': 300,  # Same DPI as in image options
            'image-dpi': 300,  # Image DPI is the same
            'image-quality': 100,  # Image quality set to maximum
        }

        # Convert HTML to PDF with the specified options
        pdf = pdfkit.from_string(resume_download.html_content, False, configuration=pdfkit_config, options=options)

        # Create HTTP response
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="resume.pdf"'
        return response

    except Resume.DoesNotExist:
        return HttpResponse("Resume not found.", status=404)

# ================================
# Save Resume as Image
# ================================
def save_resume_image(user, resume, html_content):
    """
    Convert the HTML content of a resume to an image and save it.
    """
    # Configure imgkit with path to wkhtmltoimage executable
    imgkit_config = imgkit.config(wkhtmltoimage=settings.IMGKIT_CONFIG['wkhtmltoimage'])
    img_options = {
        'format': 'png',
        'quality': '100',
        'crop-w': '2480',  # Width in pixels (A4 size at 300 DPI)
        'crop-h': '3508',  # Height in pixels (A4 size at 300 DPI)
        'zoom': '1.50',
    }

    try:
        # Convert HTML to image
        image_data = imgkit.from_string(html_content, False, config=imgkit_config, options=img_options)

        # Save image to a file-like object
        image_file = BytesIO(image_data)
        image_file.seek(0)

        # Create a ContentFile for Django
        image_content = ContentFile(image_file.read(), name=f'{resume.name}.png')

        # Save the image to the Resume instance
        resume.image.save(f'{user}_{resume.name}.png', image_content, save=True)

    except Exception as e:
        print(f"Error saving image: {e}")

# ================================
# Save Resume as PDF
# ================================
def save_resume_pdf(user, resume, html_content):
    """
    Convert the HTML content of a resume to a PDF and save it.
    """
    # Convert SafeString to a regular string if needed
    if hasattr(html_content, 'unsafe'):
        html_content_str = str(html_content)
    else:
        html_content_str = html_content

portal_resume_app/templates/portal_resume_app/base_resume.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Freshers Park - Your gateway to exciting career opportunities!">
    <meta name="keywords" content="jobs, freshers, careers, job portal, Freshers Park">
    <meta name="author" content="Freshers Park">
    <meta property="og:title" content="Freshers Park - Job Portal">
    <meta property="og:description" content="Your gateway to exciting career opportunities!">
    <meta property="og:image" content="{% static 'portal_user_app/images/favicon.png' %}">
    <meta property="og:url" content="https://www.fresherspark.in">
    <meta name="twitter:card" content="summary_large_image">
    <link href="{% static 'portal_user_app/images/favicon.ico' %}" rel="icon" type="image/x-icon">

    <title>Freshers Park | Resume Builder</title>

    <link href="{% static 'portal_resume_app/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'portal_resume_app/css/resume_index.css' %}" rel="stylesheet">
    <link href="{% static 'portal_resume_app/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'portal_resume_app/css/a4size.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <a class="navbar-brand" href="{% url 'portal_resume_app:resume_index' %}">Resume Builder</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal_resume_app:resume_index' %}"><i class="fas fa-user"></i> Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal_user_app:user_dashboard' %}"><i class="fas fa-home"></i> Home</a>
                </li>
            </ul>
        </div>
    </nav>
    
    <div>
                {% block content %}
                {% endblock %}
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <h5>About Freshers Park</h5>
            <p>Empowering fresh talent to connect with top companies. Your gateway to the best job opportunities.</p>
            <a href="#">Terms of Service</a> | <a href="#">Privacy Policy</a>
        </div>
    </footer>

    <script src="{% static 'portal_resume_app/scripts/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'portal_resume_app/scripts/jquery.3.6.0.min.js' %}"></script>
    <script src="{% static 'portal_resume_app/scripts/popper.min.j' %}s"></script>
    <script src="{% static 'portal_resume_app/scripts/bootstrap.min.js' %}"></script>
    <script src="{% static 'portal_resume_app/scripts/profile.js' %}"></script>
    <script src="{% static 'portal_resume_app/scripts/muse_efet_res_list.js' %}"></script>
</body>

</html>

portal_resume_app/templates/portal_resume_app/resume_list.html
{% extends "portal_resume_app/base_resume.html" %}

{% block content %}

<div class="page-content">
    <div class="resume-container">
        {% if resumes %}
            {% for resume in resumes %}
                <div class="resume-card">
                    <div class="resume-content">
                        {% if resume.image %}
                            <!-- Use img tag if content is an image -->
                            <img src="{{ resume.image.url }}" alt="Resume Image">
                            <div class="view-overlay">
                                <a href="{% url 'portal_resume_app:resume_display' resume.id %}" target="_blank">View</a>
                            </div>
                        {% else %}
                            <p>No image available</p>
                        {% endif %}
                    </div>
                    <a href="{% url 'portal_resume_app:resume_download' resume.id %}" class="download-link">
                        <i class="fas fa-download"></i> Download
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <p>No resumes generated</p>
        {% endif %}
    </div>
</div>

{% endblock %}

portal_resume_app/templates/portal_resume_app/resume_view.html
{% extends "portal_resume_app/base_resume.html" %}

{% load static %}

<style>    
    /* Mobile styles */
    @media (max-width: 768px) { /* You can adjust the max-width value as needed */
        .img_size {
            width: 100%; /* Image size for smaller screens */
        }
    }
</style>

{% block content %}
<div class="resume-content">
    {% if resume %}
        <img class="img_size" src="{{ resume.image.url }}" style="width: 55%;">
    {% endif %}
</div>
{% endblock %}